### ISSUE TITLE
ERROR: Invalid settings.palette.nodesExcludes When trying to enable persistent file storage node in docker

### ISSUE THREAD

**Issue by Hisma** [flowforge/flowforge#2278]
### Current Behavior

Running docker instance of flowforge by following the procedure outlined here - 
https://github.com/flowforge/flowforge/blob/main/docs/install/docker/README.md

I have it up and running successfully and I can deploy instances no problem.

I had my flowforge instance updated from a community license to an enterprise license, and I wanted access to the flowforge specific nodes, one of those being the persistent storage node.  So I followed the steps in handbook here -
https://flowforge.com/docs/user/filenodes/#enabling-persistent-file-storage
I modified the default template to allow the ability to exclude nodes by filename so I could exclude `10-file-js` as described in the handbook.  

### Expected Behavior

When checking the box I shouldn't get an error, and I should have access to the flowforge persistent file storage node.

### Steps To Reproduce

I suspended the instance, went to the instance pallet settings and added `10-file-js` to "exclude nodes by filename. 
I got this message 
![image](https://github.com/flowforge/flowforge/assets/13650167/78a32314-8112-45b5-a7b1-036cb693d578)

Here is the stacktrace of the error provided by the docker container log - 
`[2023-06-13T17:17:40.017Z] ERROR: Invalid settings.palette.nodesExcludes {"reqId":"req-4g","req":{"method":"PUT","url":"/api/v1/projects/afcedd68-20a8-42f0-be48-ac36aaca0a33","hostname":"forge.alvesmeyer.com","remoteAddress":"71.52.23.83","remotePort":52976},"res":{"statusCode":500}}
    err: {
      "type": "Error",
      "message": "Invalid settings.palette.nodesExcludes",
      "stack":
          Error: Invalid settings.palette.nodesExcludes
              at Object.validateSettings (/usr/src/forge/app/node_modules/@flowforge/flowforge/forge/db/controllers/ProjectTemplate.js:131:35)
              at Object.<anonymous> (/usr/src/forge/app/node_modules/@flowforge/flowforge/forge/routes/api/project.js:433:68)
              at runMicrotasks (<anonymous>)
              at processTicksAndRejections (node:internal/process/task_queues:96:5)
    }`

### Environment

- FlowForge version: 1.6.1
- Node.js version: 16.20.0
- npm version: 8.19.4
- Platform/OS: docker
- Browser: chrome

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by Hisma** [comment]
I realize I was several versions behind the latest on the flowforge app, so I pulled the latest version of all containers, and I'm now on version 1.8.0 of the flowforge application.  The problem still persists.  
One other thing I did on my end is went to my flowforge install folder and gave full permissions recursively inside the directory, `chmod -R 777`, just in case this was perhaps a permissions issue.  That did not fix the problem either.

**Comment by Hisma** [comment]
note - I resolved this error by following the directions in the README in the docker install - 
https://github.com/flowforge/flowforge/blob/main/docs/install/docker/README.md
Using FlowForge File Storage
Node-RED instances running in Docker do not have direct access to a persistent file system to store files or use for storing context data.

FlowForge includes a File Storage service that can be enabled to provide persistent storage.

Disabling the default File nodes
To remove the default Node-RED file nodes from the palette:
![image](https://github.com/flowforge/flowforge/assets/13650167/f073a516-bfc8-437a-9096-15df0c881c22)

Edit the Template to add 10-file.js,23-watch.js to the "Exclude nodes by filename" section


When I excluded the nodes at the base template level, rather than the instance level, everything works fine now, and the correct nodes show up in my pallet.
![image](https://github.com/flowforge/flowforge/assets/13650167/0ab0784a-9712-43c1-ab1c-1f46f2d56629)
![image](https://github.com/flowforge/flowforge/assets/13650167/288b3e59-cd4f-48b3-b512-9ab8d71e6ce2)

![image](https://github.com/flowforge/flowforge/assets/13650167/921e6be5-fcb9-4826-87f1-f30c3cf86dd6)
