### ISSUE TITLE
Support M1 (Apple Silicon) for development

### ISSUE THREAD

**Issue by ZJvandeWeg** [flowforge/flowforge#636]
### Current Behavior

Currently, without altering ones environment FlowForge can't be built with `npm run build`:

```
ERROR in ./frontend/src/pages/Login.vue?vue&type=style&index=0&id=f2ab38d8&lang=scss (./node_modules/css-loader/dist/cjs.js!./node_modules/vue-loader/dist/stylePostLoader.js!./node_modules/sass-loader/dist/cjs.js!./node_modules/vue-loader/dist/index.js??ruleSet[1].rules[10].use[0]!./frontend/src/pages/Login.vue?vue&type=style&index=0&id=f2ab38d8&lang=scss)
Module build failed (from ./node_modules/vue-loader/dist/stylePostLoader.js):
Error: PostCSS received undefined instead of CSS string
    at new Input ($USER/src/github.com/flowforge/flowforge/node_modules/postcss/lib/input.js:24:13)
    at parse ($USER/src/github.com/flowforge/flowforge/node_modules/postcss/lib/parse.js:8:15)
```

### Expected Behavior

No need to jump through hoops and pretent to be an Intel chip.

### Environment

- FlowForge version: 0.5.3
- Node.js version:
- npm version:
- Platform/OS: Apple M1 based hardware + Darwin
- Browser:

**Comment by ZJvandeWeg** [comment]
Reinstalled all npm packages, now it works
