### ISSUE TITLE
Device Agent receives 500 when trying to download snapshot

### ISSUE THREAD

**Issue by sammachin** [flowforge/flowforge#685]
### Current Behavior

When my device agent tries to fetch a snapshot the server returns a 500 error and the agent exits.
```
pi@sensehatpi:~ $ flowforge-device-agent
[2022-06-10T10:07:21.303Z] INFO: FlowForge Device Agent
[2022-06-10T10:07:21.317Z] INFO: Version: 0.0.1
[2022-06-10T10:07:21.318Z] INFO: Device: zkBLZoGoA9
[2022-06-10T10:07:21.319Z] INFO: ForgeURL: https://app.flowforge.com
[2022-06-10T10:07:21.331Z] INFO: No active snapshot
[2022-06-10T10:07:21.333Z] INFO: Starting ping thread. Interval: 30s
[2022-06-10T10:07:21.336Z] INFO: Calling home
[2022-06-10T10:07:21.550Z] INFO: New snapshot available
[2022-06-10T10:07:24.908Z] WARN: Problem getting snapshot: HTTPError: Response code 500 (Internal Server Error)
[2022-06-10T10:07:24.911Z] WARN: Error whilst starting project: TypeError: Cannot read properties of undefined (reading 'id')
/usr/lib/node_modules/@flowforge/flowforge-device-agent/lib/pinger.js:148
                await state.launcher.stop(true)
                                     ^

TypeError: Cannot read properties of undefined (reading 'stop')
    at /usr/lib/node_modules/@flowforge/flowforge-device-agent/lib/pinger.js:148:38
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```
Same experience on Prod and Staging

### Expected Behavior

flow should be deployed to device and run.

### Steps To Reproduce

Configure device agent and deploy the device.yml file to the device

Create new project, with some simple nodes (inject-debug, http in- http resp)

Create snapshot and set as device target

Start agent.

### Environment

- FlowForge version: 0.6.0 (agent 0.0.1)
- Node.js version:
- npm version:
- Platform/OS: - 
- Browser: - 

Device:
Agent: 0.0.1
Node v16.15.1
NPM 8.11.0
Raspbian GNU/Linux 11 (bullseye)
RPi 3, brand new fresh install

**Comment by hardillb** [comment]
The error on the backend looks to be in re-encrypting the flows creds

```
[2022-06-10T09:54:52.984Z] ERROR: Unexpected token y in JSON at position 0
    req: {
      "method": "GET",
      "url": "/api/v1/devices/qQGbN7xPjD/live/snapshot",
      "hostname": "forge.flowforge.dev",
      "remoteAddress": "192.168.52.48",
      "remotePort": 36212
    }
    res: {
      "statusCode": 500
    }
    reqId: "req-dmu"
    err: {
      "type": "SyntaxError",
      "message": "Unexpected token y in JSON at position 0",
      "stack":
          SyntaxError: Unexpected token y in JSON at position 0
              at JSON.parse (<anonymous>)
              at decryptCreds (/usr/src/forge/app/node_modules/@flowforge/flowforge/forge/db/controllers/Project.js:145:17)
              at Object.exportCredentials (/usr/src/forge/app/node_modules/@flowforge/flowforge/forge/db/controllers/Project.js:135:38)
              at Object.<anonymous> (/usr/src/forge/app/node_modules/@flowforge/flowforge/forge/routes/api/deviceLive.js:66:69)
              at runMicrotasks (<anonymous>)
              at processTicksAndRejections (node:internal/process/task_queues:96:5)
    }

```

**Comment by sammachin** [comment]
Flow is
```
[
    {
        "id": "3160bde897d7f122",
        "type": "tab",
        "label": "Flow 1",
        "disabled": false,
        "info": "",
        "env": []
    },
    {
        "id": "7f2bbd325070729a",
        "type": "inject",
        "z": "3160bde897d7f122",
        "name": "",
        "props": [
            {
                "p": "payload"
            },
            {
                "p": "topic",
                "vt": "str"
            }
        ],
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "",
        "payload": "",
        "payloadType": "date",
        "x": 390,
        "y": 200,
        "wires": [
            [
                "f31e3038911c0019"
            ]
        ]
    },
    {
        "id": "f31e3038911c0019",
        "type": "debug",
        "z": "3160bde897d7f122",
        "name": "",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "false",
        "statusVal": "",
        "statusType": "auto",
        "x": 690,
        "y": 200,
        "wires": []
    },
    {
        "id": "421168afca7606a7",
        "type": "http in",
        "z": "3160bde897d7f122",
        "name": "",
        "url": "/test",
        "method": "get",
        "upload": false,
        "swaggerDoc": "",
        "x": 410,
        "y": 520,
        "wires": [
            [
                "21bd0d722c915c49"
            ]
        ]
    },
    {
        "id": "21bd0d722c915c49",
        "type": "http response",
        "z": "3160bde897d7f122",
        "name": "",
        "statusCode": "",
        "headers": {},
        "x": 700,
        "y": 520,
        "wires": []
    }
]```

**Comment by hardillb** [comment]
This is resolved after ensuring that the project is created on the latest version of the NR 2.2.2 / FF 0.6.0 stack.

Still need to look at how to pick up the right credentialSecret on older stacks.

**Comment by sammachin** [comment]
Given the alpha nature of the devices feature and that this will be diminishing returns I'm proposing to close this without worrying about legacy stacks
