### ISSUE TITLE
Error thrown if device tries to report running deleted snapshot

### ISSUE THREAD

**Issue by hardillb** [flowforge/flowforge#732]
### Current Behavior

If you delete the snapshot a device is running while it is offline when it comes online and reports state it will fail as the active snapshot expects the old snapshot to still be in the database (as a foreign key)

```
[2022-06-27T14:19:45.608Z] ERROR: SQLITE_CONSTRAINT: FOREIGN KEY constraint failed
    req: {
      "method": "POST",
      "url": "/api/v1/devices/AnQLYML6kJ/live/state",
      "hostname": "localhost:3000",
      "remoteAddress": "127.0.0.1",
      "remotePort": 59828
    }
    res: {
      "statusCode": 500
    }
    reqId: "req-2"
    err: {
      "type": "ForeignKeyConstraintError",
      "message": "SQLITE_CONSTRAINT: FOREIGN KEY constraint failed",
      "stack":
          Error
              at Database.<anonymous> (/opt/share/projects/flowforge/flowforge-dev-env/node_modules/sequelize/lib/dialects/sqlite/query.js:179:27)
              at /opt/share/projects/flowforge/flowforge-dev-env/node_modules/sequelize/lib/dialects/sqlite/query.js:177:50
              at new Promise (<anonymous>)
              at Query.run (/opt/share/projects/flowforge/flowforge-dev-env/node_modules/sequelize/lib/dialects/sqlite/query.js:177:12)
              at /opt/share/projects/flowforge/flowforge-dev-env/node_modules/sequelize/lib/sequelize.js:311:28
              at async SQLiteQueryInterface.update (/opt/share/projects/flowforge/flowforge-dev-env/node_modules/sequelize/lib/dialects/abstract/query-interface.js:355:12)
              at async model.save (/opt/share/projects/flowforge/flowforge-dev-env/node_modules/sequelize/lib/model.js:2432:35)
              at async Object.updateState (/opt/share/projects/flowforge/flowforge-dev-env/packages/flowforge/forge/db/controllers/Device.js:21:9)
              at async Object.<anonymous> (/opt/share/projects/flowforge/flowforge-dev-env/packages/flowforge/forge/routes/api/deviceLive.js:33:9)
      "name": "SequelizeForeignKeyConstraintError",
      "parent": {
        "type": "Error",
        "message": "SQLITE_CONSTRAINT: FOREIGN KEY constraint failed",
        "stack":
            Error: SQLITE_CONSTRAINT: FOREIGN KEY constraint failed
        "errno": 19,
        "code": "SQLITE_CONSTRAINT",
        "sql": "UPDATE `Devices` SET `state`=$1,`lastSeenAt`=CURRENT_TIMESTAMP,`activeSnapshotId`=$2,`updatedAt`=$3 WHERE `id` = $4"
      },
      "original": {
        "type": "Error",
        "message": "SQLITE_CONSTRAINT: FOREIGN KEY constraint failed",
        "stack":
            Error: SQLITE_CONSTRAINT: FOREIGN KEY constraint failed
        "errno": 19,
        "code": "SQLITE_CONSTRAINT",
        "sql": "UPDATE `Devices` SET `state`=$1,`lastSeenAt`=CURRENT_TIMESTAMP,`activeSnapshotId`=$2,`updatedAt`=$3 WHERE `id` = $4"
      },
      "sql": "UPDATE `Devices` SET `state`=$1,`lastSeenAt`=CURRENT_TIMESTAMP,`activeSnapshotId`=$2,`updatedAt`=$3 WHERE `id` = $4",
      "parameters": {}
    }
```

This means that the checkin fails and the device does not download the new snapshot

### Expected Behavior

Check in should complete and report the new snapshot id

### Steps To Reproduce

- Create device
- Add to a project
- Take snapshort of project
- Mark snapshot active
- Start device
- Stop device
- Create new snapshot
- Mark new snapshot active
- Delete old snapshot
- Start Device

### Environment

- FlowForge version: 0.6.2
- Node.js version: 16.x
- npm version: 8.x
- Platform/OS: Linux
- Browser: NA

**Comment by hardillb** [comment]
Temp fix for this went into #734

https://github.com/flowforge/flowforge/blob/2948fe57dcea7d4b80f527da3751b29ed3fc16bd/forge/db/controllers/Device.js#L18-L21

Should review to see if this is sufficient

**Comment by hardillb** [comment]
I'll add a test specifically for this and then I think we can move this to done
