### ISSUE TITLE
Loading Node-Red logs is stuck in a loop

### ISSUE THREAD

**Issue by sammachin** [flowforge/flowforge#735]
### Current Behavior

Trying to load the logs for a project and the loading screen just sits there looping.

Looking at the developer tools it is making the request for /logs and getting back a JSON object but that is then being re-sent every ~5s
![image](https://user-images.githubusercontent.com/187645/176126495-37513194-c3f7-4ce4-91fa-5c5a9fc4492c.png)

The error in the browser console with this is:
```
Uncaught (in promise) TypeError: e.msg.replace is not a function
    at main.js:1:230607
    at Array.forEach (<anonymous>)
    at Proxy.loadItems (main.js:1:230461)
```

### Expected Behavior

Logs should load 

### Steps To Reproduce

The `comfortable-golden-winged-warbler-6949` on the flowforge team in flowforge.cloud demonstrates the issue.

Other projects load logs fine.

Logs for this project shouldn't be that large its just a few stop/starts as far as I can see in the log data thats returned

### Environment

- FlowForge version: 0.6.2
- Node.js version: 16?
- npm version: 8
- Platform/OS: Mac M1 12.3.1
- Browser: Chrome  103.0.5060.53

**Comment by sammachin** [comment]
looks like the polling response is sending the same data back though each time?
This is the response to /logs
```
{"meta":{"next_cursor":"16564028766520000","previous_cursor":"-16564015185230000"},"log":[{"ts":"16564015185230000","level":"info","msg":"Started flows"},{"ts":"16564015255210000","level":"info","msg":"Stopping flows"},{"ts":"16564015255220000","level":"info","msg":"Stopped flows"},{"ts":"16564015255230000","level":"info","msg":"Starting flows"},{"ts":"16564015255250000","level":"error","type":"whin-receive","id":"7be8b42a8680080e","msg":{}},{"ts":"16564015255260000","level":"info","msg":"Started flows"},{"ts":"16564015347620000","level":"info","msg":"Stopping flows"},{"ts":"16564015347620001","level":"info","msg":"Stopped flows"},{"ts":"16564015347630000","level":"info","msg":"Starting flows"},{"ts":"16564015347650000","level":"info","msg":"Started flows"},{"ts":"16564023447250000","level":"info","msg":"Stopping flows"},{"ts":"16564023447250001","level":"info","msg":"Stopped flows"},{"ts":"16564023447270000","level":"info","msg":"Starting flows"},{"ts":"16564023447280000","level":"info","msg":"Started flows"},{"ts":"16564023479400000","level":"info","msg":"Stopping flows"},{"ts":"16564023479410000","level":"info","msg":"Stopped flows"},{"ts":"16564023479420000","level":"info","msg":"Starting flows"},{"ts":"16564023479420001","level":"info","msg":"Started flows"},{"ts":"16564023502420000","level":"info","msg":"Stopping flows"},{"ts":"16564023502420001","level":"info","msg":"Stopped flows"},{"ts":"16564023502430000","level":"info","msg":"Starting flows"},{"ts":"16564023502440000","level":"info","msg":"Started flows"},{"ts":"16564023553890000","level":"info","msg":"Stopping flows"},{"ts":"16564023553890001","level":"info","msg":"Stopped flows"},{"ts":"16564023553900000","level":"info","msg":"Starting flows"},{"ts":"16564023553910000","level":"info","msg":"Started flows"},{"ts":"16564028766490000","level":"info","msg":"Stopping flows"},{"ts":"16564028766500000","level":"info","msg":"Stopped flows"},{"ts":"16564028766510000","level":"info","msg":"Starting flows"},{"ts":"16564028766520000","level":"info","msg":"Started flows"}]}
```
