### ISSUE TITLE
There is a limit version of old node red version?

### ISSUE THREAD

**Issue by node-red-italia** [flowforge/flowforge#795]
### Current Behavior

Hi @knolleary , I am Folgore. I have add a stack of my old version of node-red (1.2.7 and 2.2.2). After create a stack and the new project when I open the editor, node red show the popup to sign in. I click to sign in and I received  this message:

TypeError: done is not a function
    at verify (/opt/flowforge/app/node_modules/@flowforge/nr-auth/lib/index.js:67:21)
    at Strategy._verify (/opt/flowforge/var/stacks/1.2.7/node_modules/@node-red/editor-api/lib/auth/index.js:188:32)
    at /opt/flowforge/app/node_modules/passport-oauth2/lib/strategy.js:205:24
    at /opt/flowforge/app/node_modules/@flowforge/nr-auth/lib/strategy.js:21:13
    at passBackControl (/opt/flowforge/app/node_modules/oauth/lib/oauth2.js:134:9)
    at IncomingMessage.<anonymous> (/opt/flowforge/app/node_modules/oauth/lib/oauth2.js:157:7)
    at IncomingMessage.emit (node:events:539:35)
    at endReadableNT (node:internal/streams/readable:1345:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)

The stack with last node-red version works correctly

Thank's a lot

### Environment

- FlowForge version:
- Node.js version:
- npm version:
- Platform/OS:
- Browser:

**Comment by knolleary** [comment]
I hadn't considered users might want to use Node-RED 1.x on the platform given how old it is. The authentication plugin we use will require Node-RED 2.x.

Is there a particular release you need to run 1.x when creating a new project?

**Comment by node-red-italia** [comment]
Yes, but I want to upgrade the 1.x version. I have not a problem. 

Thank'you very much for the support

**Comment by hardillb** [comment]
iirc it needed at least 2.1.x when I tested. And we did decide not to support before 2.2.x as a rule
