### ISSUE TITLE
Invitations left for deleted teams

### ISSUE THREAD

**Issue by hardillb** [flowforge/flowforge#923]
### Current Behavior

If you delete a team that has an outstanding invitation the invitation is left in the database.

This causes a 500 error when the admin lists invites and when the invited user logs in

```
[2022-08-26T10:06:23.818Z] ERROR: Cannot read properties of null (reading 'get') {"reqId":"req-1b","req":{"method":"GET","url":"/api/v1/user/invitations","hostname":"localhost:3000","remoteAddress":"127.0.0.1","remotePort":52748},"res":{"statusCode":500}}
    err: {
      "type": "TypeError",
      "message": "Cannot read properties of null (reading 'get')",
      "stack":
          TypeError: Cannot read properties of null (reading 'get')
              at Object.teamSummary (/opt/share/projects/flowforge/flowforge-dev-env/packages/flowforge/forge/db/views/Team.js:19:24)
              at /opt/share/projects/flowforge/flowforge-dev-env/packages/flowforge/forge/db/views/Invitation.js:10:41
              at Array.map (<anonymous>)
              at Object.invitationList (/opt/share/projects/flowforge/flowforge-dev-env/packages/flowforge/forge/db/views/Invitation.js:3:28)
              at Object.<anonymous> (/opt/share/projects/flowforge/flowforge-dev-env/packages/flowforge/forge/routes/api/userInvitations.js:14:48)
```

### Expected Behavior

Invites for deleted teams should be removed

### Steps To Reproduce

- Create a team
- Invite a user
- Delete the team
- Log in as invited user

### Environment

- FlowForge version: 0.8
- Node.js version: 16.x
- npm version: 8.x
- Platform/OS: Linux
- Browser: Chrome

**Comment by sammachin** [comment]
verified in staging
