### ISSUE TITLE
/api/v1/user/projects endpoint broken

### ISSUE THREAD

**Issue by knolleary** [flowforge/flowforge#982]
### Current Behavior

The `/api/v1/user/projects` is broken.

```
{
"statusCode": 500,
"error": "Internal Server Error",
"message": "ProjectType is not associated to Team!"
}
```

```
err: {
      "type": "EagerLoadingError",
      "message": "ProjectType is not associated to Team!",
      "stack":
          SequelizeEagerLoadingError: ProjectType is not associated to Team!
              at Function._getIncludedAssociation (/Users/nol/code/flowforge/flowforge-dev-env/node_modules/sequelize/lib/model.js:565:13)
              at Function._validateIncludedElement (/Users/nol/code/flowforge/flowforge-dev-env/node_modules/sequelize/lib/model.js:502:53)
              at /Users/nol/code/flowforge/flowforge-dev-env/node_modules/sequelize/lib/model.js:421:37
              at Array.map (<anonymous>)
              at Function._validateIncludedElements (/Users/nol/code/flowforge/flowforge-dev-env/node_modules/sequelize/lib/model.js:417:39)
              at Function._validateIncludedElement (/Users/nol/code/flowforge/flowforge-dev-env/node_modules/sequelize/lib/model.js:557:38)
              at /Users/nol/code/flowforge/flowforge-dev-env/node_modules/sequelize/lib/model.js:421:37
              at Array.map (<anonymous>)
              at Function._validateIncludedElements (/Users/nol/code/flowforge/flowforge-dev-env/node_modules/sequelize/lib/model.js:417:39)
              at Function.findAll (/Users/nol/code/flowforge/flowforge-dev-env/node_modules/sequelize/lib/model.js:1118:12)
      "name": "SequelizeEagerLoadingError"
    }
```

This endpoint was intended to return the list of projects associated with a user. However we do not use that endpoint anywhere in the frontend.

### Expected Behavior

Either:

1. make the end-point work
2. remove it as it is unused

### Steps To Reproduce

1. Open `http://localhost:3000/api/v1/user/projects`

**Comment by sammachin** [comment]
Verified on staging (returns 404)
